### ISSUE TITLE
Add IP to subjectalternativename

### ISSUE THREAD

**Issue by LanceloteHK** [damienbod/AspNetCoreCertificates#37]
Hello, now the SubjectAlternativeName only support adding dnsname and email. Would you consider adding support to add IP to SubjectAlternativeName too? Thank you.

**Comment by damienbod** [comment]
Hi @LanceloteHK This sounds like a good idea. Maybe a PR? 

If not, I will add this next time I work on this. Thanks for reporting

Greetings Damien
