### ISSUE TITLE
Issue of Byte order in CreateCertificates.ChainedConfiguration() at line #315: BitConverter.GetBytes(unixTime);

### ISSUE THREAD

**Issue by jlewis666** [damienbod/AspNetCoreCertificates#39]
Hi,

In the source file https://github.com/damienbod/AspNetCoreCertificates/blob/main/src/CertificateManager/CreateCertificates.cs:

at line #315:

var serial = BitConverter.GetBytes(unixTime);

If the host PC is Intel, then the byte order returned is Little Endian.

But the method called in the line that follows that consumes serial expects 'serial' to be in Big Endian Order.

**Comment by damienbod** [comment]
@jlewis666 Thanks for reporting, would you like to create a PR which fixes this?

Greetings Damien
